import 'package:flutter_riverpod/flutter_riverpod.dart';

import '../models/movie.dart';

// TODO: Add dedicated landscape banners for movies that currently use posters.
final mockMoviesProvider = Provider<List<Movie>>(
  (ref) => const [
    Movie(
      id: 'inception',
      title: 'INCEPTION',
      ageRating: 'T13',
      duration: '148 phút',
      rating: 8.8,
      ratingCount: '12.4k',
      genre: 'Khoa học viễn tưởng',
      genreTags: ['Sci-Fi Cyber', 'Pure Action'],
      tagline:
          'Giấc mơ trong giấc mơ — đỉnh cao điện ảnh của Christopher Nolan.',
      posterAsset: 'assets/mock/movies/inception-poster.jpg',
      bannerAsset: 'assets/mock/movies/inception-banner.jpg',
      format: 'IMAX Laser',
      isNowShowing: true,
    ),
    Movie(
      id: 'avengers-endgame',
      title: 'AVENGERS: ENDGAME',
      ageRating: '13+',
      duration: '181 phút',
      rating: 9.4,
      ratingCount: '12.8k',
      genre: 'Siêu anh hùng',
      genreTags: ['Sci-Fi Cyber', 'Pure Action'],
      tagline: 'Một phần của hành trình chính là hồi kết.',
      posterAsset: 'assets/mock/movies/avengers-endgame-poster.jpg',
      format: 'IMAX 3D',
      isNowShowing: true,
    ),
    Movie(
      id: 'joker',
      title: 'Joker',
      ageRating: '18+',
      duration: '122 phút',
      rating: 8.9,
      genre: 'Tâm lý',
      genreTags: ['Cinematic Noir'],
      tagline: 'Một câu chuyện về thành phố và con người bên lề.',
      posterAsset: 'assets/mock/movies/joker-poster.jpg',
      isNowShowing: true,
    ),
    Movie(
      id: 'spider-verse',
      title: 'Spider-Verse',
      ageRating: 'P',
      duration: '117 phút',
      rating: 9.1,
      ratingCount: '15.2k',
      genre: 'Hoạt hình',
      genreTags: ['Vision Quest Hoạt hình'],
      tagline: 'Bước vào thế giới Người Nhện đa vũ trụ.',
      posterAsset: 'assets/mock/movies/spider-verse-poster.png',
      isNowShowing: true,
    ),
    Movie(
      id: 'coco',
      title: 'Coco',
      ageRating: 'P',
      duration: '105 phút',
      rating: 9.3,
      genre: 'Hoạt hình',
      genreTags: ['Vision Quest Hoạt hình'],
      tagline: 'Một hành trình đầy màu sắc về gia đình và âm nhạc.',
      posterAsset: 'assets/mock/movies/coco-poster.jpg',
      isNowShowing: true,
    ),
    Movie(
      id: 'the-green-mile',
      title: 'The Green Mile',
      ageRating: '16+',
      duration: '189 phút',
      rating: 8.6,
      genre: 'Chính kịch',
      tagline: 'Một câu chuyện khó quên về lòng trắc ẩn.',
      posterAsset: 'assets/mock/movies/the-green-mile-poster.jpg',
      releaseDate: 'Khởi chiếu 28.10',
    ),
    Movie(
      id: 'parasite',
      title: 'Parasite (Ký Sinh Trùng)',
      ageRating: '18+',
      duration: '132 phút',
      rating: 8.5,
      genre: 'Tâm lý, kịch tính',
      tagline: 'Hai gia đình, hai thế giới.',
      posterAsset: 'assets/mock/movies/parasite-poster.jpg',
      releaseDate: 'Khởi chiếu 05.11',
    ),
    Movie(
      id: 'la-la-land',
      title: 'La La Land',
      ageRating: 'P',
      duration: '128 phút',
      rating: 8.9,
      genre: 'Âm nhạc, lãng mạn',
      tagline: 'Một chuyện tình giữa những giấc mơ.',
      posterAsset: 'assets/mock/movies/la-la-land-poster.jpg',
      releaseDate: 'Khởi chiếu 12.11',
    ),
  ],
);
