import 'package:flutter_riverpod/flutter_riverpod.dart';

import '../models/ticket_order.dart';

final mockOrdersProvider = Provider<List<TicketOrder>>(
  (ref) => const [
    TicketOrder(
      id: 'ord-1',
      ticketCode: 'CP-INC-20260914-C4C5',
      movieId: 'inception',
      movieTitle: 'Inception',
      moviePoster: 'assets/mock/movies/inception-poster.jpg',
      ageRating: '16+',
      format: '2D Dolby Atmos • Phụ đề',
      cinemaLocation: 'CineAI Central • Phòng C',
      roomName: 'Phòng C',
      dateTime: '20:30 • T.Hai, 14/09/2026',
      seats: ['C4', 'C5'],
      seatsTypeLabel: '2 vé (VIP)',
      concessionsSummary: '1x Combo Couple',
      totalPrice: 269000,
      status: TicketOrderStatus.upcoming,
      statusLabel: 'Sắp chiếu (Trong 45 phút)',
    ),
    TicketOrder(
      id: 'ord-2',
      ticketCode: 'CP-771204',
      movieId: 'avengers-endgame',
      movieTitle: 'Avengers: Endgame',
      moviePoster: 'assets/mock/movies/avengers-endgame-poster.jpg',
      ageRating: '13+',
      format: '3D IMAX • Phụ đề',
      cinemaLocation: 'CineAI Central • Phòng A',
      roomName: 'Phòng A',
      dateTime: '10/08/2026',
      seats: ['G12', 'G13'],
      seatsTypeLabel: '2 vé',
      concessionsSummary: 'Combo Solo',
      totalPrice: 340000,
      status: TicketOrderStatus.completed,
      statusLabel: 'Đã xem',
    ),
    TicketOrder(
      id: 'ord-3',
      ticketCode: 'CP-639102',
      movieId: 'spider-verse',
      movieTitle: 'Spider-Man: Into the Spider-Verse',
      moviePoster: 'assets/mock/movies/spider-verse-poster.png',
      ageRating: 'P',
      format: '2D Lồng tiếng • Chuẩn rạp',
      cinemaLocation: 'CineAI Central • Phòng B',
      roomName: 'Phòng B',
      dateTime: '28/07/2026',
      seats: ['E8'],
      seatsTypeLabel: '1 vé',
      concessionsSummary: 'Không kèm F&B',
      totalPrice: 115000,
      status: TicketOrderStatus.completed,
      statusLabel: 'Đã hoàn tất',
    ),
  ],
);
